#!/bin/bash
# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

port=$(ynh_app_setting_set $app port)
path=$(ynh_app_setting_set $app path)
admin=$(ynh_app_setting_set $app admin)
domain=$(ynh_app_setting_set $app domain)
is_public=$(ynh_app_setting_set $app is_public)

#=================================================
# FIX OLD THINGS
#=================================================
cp ../conf/rsyslogd.conf /etc/rsyslog.d/$app.conf
service rsyslog restart
ynh_use_logrotate "/var/log/wisemapping/$app.log"

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
    # restore it if the upgrade fails
    ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK THE PATH
#=================================================
# Verify and correct path syntax
path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
